version: "3.9"
services:
  postgres:
    image: postgres:13
    environment: 
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=aaa
      - POSTGRES_DB=simple_bank
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8085:8085"
    environment:
      - DATASOURCE_URL=postgres://root:aaa@postgres:5432/simple_bank?sslmode=disable
    depends_on:
      - postgres
    entrypoint: [ "/app/wait-for.sh", "postgres:5432" , "--", "/app/start.sh"]
    command: [ "/app/main" ]